### IMPORTING DATA

In [94]:
import pandas as pd

In [95]:
df=pd.read_csv(r"C:\Users\minsh\Desktop\OJT 2 sem\Project_4.1\Data\samplesuperstore.csv")

### DATA INSPECTION

In [96]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [97]:
print(df.shape)

(10194, 21)

In [98]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [99]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [100]:
df[["Sales","Quantity","Discount","Profit"]].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [101]:
print("duplicated rows:",df.duplicated().sum())

duplicated rows: 0

In [102]:
dupes=df[df.duplicated(subset=["Order ID"],keep=False)]
print(dupes.shape)
dupes.head()

(7601, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
5,6,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
6,7,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796

### DATA CLEANING

In [103]:
df["Order Date"]=pd.to_datetime(df["Order Date"])
df["Ship Date"]=pd.to_datetime(df["Ship Date"])

In [104]:
df["Shipping Days"]=(df["Ship Date"]-df["Order Date"])
print(df.groupby('Region')["Shipping Days"].mean().round(1))

Region
Central   4 days 01:17:05.267665952
East      3 days 21:55:05.827193570
South               3 days 23:01:20
West      3 days 22:34:07.340916077
Name: Shipping Days, dtype: timedelta64[ns]

In [105]:
df["Profit Margin %"]=((df["Profit"]/df["Sales"])*100).round(2)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Profit Margin %
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4 days,33.75
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4 days,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4 days,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4 days,-23.75
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,7 days,25.00

In [106]:
print(df.groupby("Sub-Category")["Profit Margin %"].mean().sort_values(ascending=False).head().round(1))

Sub-Category
Paper        42.5
Labels       42.5
Envelopes    42.3
Copiers      32.0
Fasteners    30.6
Name: Profit Margin %, dtype: float64

In [107]:
df["Order Year"]=df["Order Date"].dt.year

In [108]:
df=df.rename(columns={"Row ID":"row_id",
                   "Order ID":"order_id",
                   "Order Date":"order_date",
                   "Ship Date":"ship_date",
                   "Ship Mode":"ship_mode",
                   "Customer ID":"customer_id",
                   "Customer Name":"customer_name",
                   "Segment":"segment",
                   'Country/Region':'country/region', 
                   'City':'city',
                   'State/Province':'state/province',
                   'Postal Code':'postal_code', 
                   'Region':'region',
                   'Product ID':'product_id', 
                   'Category':'category',
                   'Sub-Category':'sub-category',
                   'Product Name':'product_name',
                   'Sales':'sales',
                   'Quantity':'quantity',
                   'Discount':'discount',
                   'Profit':'profit', 
                   'Shipping Days':'shipping_days', 
                   'Profit Margin %':'profit_margin_%', 
                   'Order Year':'order_year'
                   })

In [109]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country/region', 'city',
       'state/province', 'postal_code', 'region', 'product_id', 'category',
       'sub-category', 'product_name', 'sales', 'quantity', 'discount',
       'profit', 'shipping_days', 'profit_margin_%', 'order_year'],
      dtype='object')

### EXPORTING DATA

In [110]:
df.to_csv(r"C:\Users\minsh\Desktop\OJT 2 sem\Project_4.1\Output\samplesuperstore_clean.csv")